### ISSUE TITLE
kinto-emailer plugin tries to create debug directory even though no mail configuration is specified

### ISSUE THREAD

**Issue by jasonthomas** [Kinto/kinto-emailer#33]
This occurs with the kinto-dist docker image and with no mail configuration specified. 

```
GMar 01 21:05:13 ip-172-31-23-160 docker[6965]: Setting up 'changes' listener
Mar 01 21:05:14 ip-172-31-23-160 docker[6965]: Traceback (most recent call last):
Mar 01 21:05:14 ip-172-31-23-160 docker[6965]: File "app.wsgi", line 23, in <module>
Mar 01 21:05:14 ip-172-31-23-160 docker[6965]: application = main(config.items('DEFAULT'), **dict(config.items('app:main')))
Mar 01 21:05:14 ip-172-31-23-160 docker[6965]: File "/usr/local/lib/python3.5/site-packages/kinto/__init__.py", line 52, in main
Mar 01 21:05:14 ip-172-31-23-160 docker[6965]: default_settings=DEFAULT_SETTINGS)
Mar 01 21:05:14 ip-172-31-23-160 docker[6965]: File "/usr/local/lib/python3.5/site-packages/kinto/core/initialization.py", line 586, in initialize
Mar 01 21:05:14 ip-172-31-23-160 docker[6965]: config.include("kinto.core", route_prefix=api_version)
Mar 01 21:05:14 ip-172-31-23-160 docker[6965]: File "/usr/local/lib/python3.5/site-packages/pyramid/config/__init__.py", line 800, in include
Mar 01 21:05:14 ip-172-31-23-160 docker[6965]: c(configurator)
Mar 01 21:05:14 ip-172-31-23-160 docker[6965]: File "/usr/local/lib/python3.5/site-packages/kinto/core/__init__.py", line 173, in includeme
Mar 01 21:05:14 ip-172-31-23-160 docker[6965]: config.include(app)
Mar 01 21:05:14 ip-172-31-23-160 docker[6965]: File "/usr/local/lib/python3.5/site-packages/pyramid/config/__init__.py", line 800, in include
Mar 01 21:05:14 ip-172-31-23-160 docker[6965]: c(configurator)
Mar 01 21:05:14 ip-172-31-23-160 docker[6965]: File "/usr/local/lib/python3.5/site-packages/kinto_emailer/__init__.py", line 179, in includeme
Mar 01 21:05:14 ip-172-31-23-160 docker[6965]: config.include('pyramid_mailer' + ('.debug' if debug else ''))
Mar 01 21:05:14 ip-172-31-23-160 docker[6965]: File "/usr/local/lib/python3.5/site-packages/pyramid/config/__init__.py", line 800, in include
Mar 01 21:05:14 ip-172-31-23-160 docker[6965]: c(configurator)
Mar 01 21:05:14 ip-172-31-23-160 docker[6965]: File "/usr/local/lib/python3.5/site-packages/pyramid_mailer/debug.py", line 8, in includeme
Mar 01 21:05:14 ip-172-31-23-160 docker[6965]: mailer = DebugMailer(path)
Mar 01 21:05:14 ip-172-31-23-160 docker[6965]: File "/usr/local/lib/python3.5/site-packages/pyramid_mailer/mailer.py", line 40, in __init__
Mar 01 21:05:14 ip-172-31-23-160 docker[6965]: makedirs(top_level_directory)
Mar 01 21:05:14 ip-172-31-23-160 docker[6965]: File "/usr/local/lib/python3.5/os.py", line 241, in makedirs
Mar 01 21:05:14 ip-172-31-23-160 docker[6965]: mkdir(name, mode)
Mar 01 21:05:14 ip-172-31-23-160 docker[6965]: PermissionError: [Errno 13] Permission denied: '/app/mail'
Mar 01 21:05:14 ip-172-31-23-160 docker[6965]: unable to load app 0 (mountpoint='') (callable not found or import error)
Mar 01 21:05:14 ip-172-31-23-160 docker[6965]: *** no app loaded. going in full dynamic mode ***
```

**Comment by leplatrem** [comment]
It looks like the *debug emailer* is used. This one will write emails into a folder instead of sending them for real, which makes integration tests easier.

I just read the code again and it should not use it by default. I will double check if there is some kind of fallback when no host is configured or something.

In the mean time, to avoid this, you could either:
* not mention `kinto_emailer` in the `kinto.includes` setting if not configured
* configure the mailer options
* create that `/app/mail` folder with appropriate permissions

**Comment by jasonthomas** [comment]
It looks like I was not configuring 'KINTO_INI' environment variable correctly which was causing app.wsgi to fall back to the default config distributed with kinto-dist which has mail debug enabled.

I think this is actually not a issue. Maybe we need to update app.wsgi not to have a fall back and fail if there is a issue.
